name: Hello World

on: 
  push:
    braches:
      - main
      - develop

jobs:
  hello-world:
    runs-on: ubuntu-24.04

    steps:
      - name: Print hello world
      # echo : 출력한다는 의미
        run: echo 'Hello World'

  hello-secret:
    runs-on: ubuntu-24.04

    steps:
      - name: Print Secret
        run: echo '${{ secrets.MY_SECRET}}'